version: '3.1'
services:
  springapp:
    image: jansy/spring-boot-mongo:1
    ports:
    - 9090:8080
    networks:
    - springappnetwork
  mongo:
    image: mongo
    volumes:
    - mongodb:/data/db
    networks:
    - springappnetwork
volumes:
  mongodb:
   external: true
networks:
  springappnetwork:
    external: true
